services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "1323:1323"
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"